
//2×× Success
const HTTP_OK = 200;

//4×× Client Error
const HTTP_BAD_REQUEST = 400;
const HTTP_FORBIDDEN = 403;

//5×× Server Error
const HTTP_INTERNAL_SERVER_ERROR = 500;

module.exports = {
    HTTP_OK: HTTP_OK,
    HTTP_BAD_REQUEST: HTTP_BAD_REQUEST,
    HTTP_FORBIDDEN: HTTP_FORBIDDEN,
    HTTP_INTERNAL_SERVER_ERROR: HTTP_INTERNAL_SERVER_ERROR,
};